name: ntm

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  format:
    exec: dart format --set-exit-if-changed .
    description: Run `dart format` in all packages.
  analyze:
    exec: dart analyze --fatal-infos .
    description: Run `dart analyze` in all packages.
  test:
    exec: dart test .
    description: Run `dart test` in all packages.
