name: ntm_cli
description: A command line tool to interpret ntm code.
version: 0.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  ntm:
    path: ../ntm
  ntm_core:
    path: ../ntm_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  test_process: ^2.0.2
