name: ntm_ast
description: The ntm ast nodes.
version: 0.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  ntm_core:
    path: ../ntm_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
