name: ntm
description: A starting point for Dart libraries or applications.
version: 0.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  freezed_annotation: ^2.1.0

dev_dependencies:
  freezed: ^2.1.0+1
  lints: ^2.0.0
  path: ^1.8.2
  test: ^1.16.0
