name: ntm
description: A library that parses and interprets ntm text files.
version: 0.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  ntm_core:
    path: ../ntm_core
  ntm_interpreter:
    path: ../ntm_interpreter
  ntm_parser:
    path: ../ntm_parser
  ntm_scanner:
    path: ../ntm_scanner

dev_dependencies:
  lints: ^2.0.0
  path: ^1.8.2
  test: ^1.21.4
