name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub global activate melos
      - run: melos bootstrap
      - run: melos run format
      - run: melos run analyze
      - run: dart pub global activate coverage
      - run: melos run test-coverage
      - run: melos run format-coverage
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v2
        with:
          flags: ntm,ntm_ast,ntm_cli,ntm_core,ntm_interpreter,ntm_parser,ntm_scanner
  spelling:
    # Verifies there is no spelling errors in the code.
    runs-on: ubuntu-latest
    name: Check code spelling
    steps:
      - uses: actions/checkout@v3
      - name: Check spelling
        uses: streetsidesoftware/cspell-action@v2
